// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calendars.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCalendar = `-- name: CreateCalendar :one
INSERT INTO calendars (slug, unit_id, name, creation_policy, visibility, participation, participant_visibility, color, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, slug, unit_id, name, creation_policy, visibility, participation, participant_visibility, color, sort_order, created_at, updated_at
`

type CreateCalendarParams struct {
	Slug                  string
	UnitID                int64
	Name                  string
	CreationPolicy        string
	Visibility            string
	Participation         string
	ParticipantVisibility string
	Color                 pgtype.Text
	SortOrder             int32
}

func (q *Queries) CreateCalendar(ctx context.Context, arg CreateCalendarParams) (Calendar, error) {
	row := q.db.QueryRow(ctx, createCalendar,
		arg.Slug,
		arg.UnitID,
		arg.Name,
		arg.CreationPolicy,
		arg.Visibility,
		arg.Participation,
		arg.ParticipantVisibility,
		arg.Color,
		arg.SortOrder,
	)
	var i Calendar
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.UnitID,
		&i.Name,
		&i.CreationPolicy,
		&i.Visibility,
		&i.Participation,
		&i.ParticipantVisibility,
		&i.Color,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCalendar = `-- name: DeleteCalendar :exec
DELETE FROM calendars WHERE id = $1
`

func (q *Queries) DeleteCalendar(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCalendar, id)
	return err
}

const deleteCalendarCustomViewers = `-- name: DeleteCalendarCustomViewers :exec
DELETE FROM calendar_custom_viewers WHERE calendar_id = $1
`

func (q *Queries) DeleteCalendarCustomViewers(ctx context.Context, calendarID int64) error {
	_, err := q.db.Exec(ctx, deleteCalendarCustomViewers, calendarID)
	return err
}

const getCalendarByID = `-- name: GetCalendarByID :one
SELECT id, slug, unit_id, name, creation_policy, visibility, participation, participant_visibility, color, sort_order, created_at, updated_at FROM calendars WHERE id = $1
`

func (q *Queries) GetCalendarByID(ctx context.Context, id int64) (Calendar, error) {
	row := q.db.QueryRow(ctx, getCalendarByID, id)
	var i Calendar
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.UnitID,
		&i.Name,
		&i.CreationPolicy,
		&i.Visibility,
		&i.Participation,
		&i.ParticipantVisibility,
		&i.Color,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCalendarBySlug = `-- name: GetCalendarBySlug :one
SELECT id, slug, unit_id, name, creation_policy, visibility, participation, participant_visibility, color, sort_order, created_at, updated_at FROM calendars WHERE slug = $1
`

func (q *Queries) GetCalendarBySlug(ctx context.Context, slug string) (Calendar, error) {
	row := q.db.QueryRow(ctx, getCalendarBySlug, slug)
	var i Calendar
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.UnitID,
		&i.Name,
		&i.CreationPolicy,
		&i.Visibility,
		&i.Participation,
		&i.ParticipantVisibility,
		&i.Color,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCalendarWithUnit = `-- name: GetCalendarWithUnit :one
SELECT c.id, c.slug, c.unit_id, c.name, c.creation_policy, c.visibility,
    c.participation, c.participant_visibility, c.color, c.sort_order,
    c.created_at, c.updated_at,
    u.name AS unit_name, u.slug AS unit_slug
FROM calendars c
JOIN units u ON c.unit_id = u.id
WHERE c.id = $1
`

type GetCalendarWithUnitRow struct {
	ID                    int64
	Slug                  string
	UnitID                int64
	Name                  string
	CreationPolicy        string
	Visibility            string
	Participation         string
	ParticipantVisibility string
	Color                 pgtype.Text
	SortOrder             int32
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	UnitName              string
	UnitSlug              string
}

func (q *Queries) GetCalendarWithUnit(ctx context.Context, id int64) (GetCalendarWithUnitRow, error) {
	row := q.db.QueryRow(ctx, getCalendarWithUnit, id)
	var i GetCalendarWithUnitRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.UnitID,
		&i.Name,
		&i.CreationPolicy,
		&i.Visibility,
		&i.Participation,
		&i.ParticipantVisibility,
		&i.Color,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UnitName,
		&i.UnitSlug,
	)
	return i, err
}

const getCustomViewerUnits = `-- name: GetCustomViewerUnits :many
SELECT u.id, u.name, u.slug
FROM calendar_custom_viewers ccv
JOIN units u ON ccv.unit_id = u.id
WHERE ccv.calendar_id = $1
ORDER BY u.name
`

type GetCustomViewerUnitsRow struct {
	ID   int64
	Name string
	Slug string
}

func (q *Queries) GetCustomViewerUnits(ctx context.Context, calendarID int64) ([]GetCustomViewerUnitsRow, error) {
	rows, err := q.db.Query(ctx, getCustomViewerUnits, calendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCustomViewerUnitsRow
	for rows.Next() {
		var i GetCustomViewerUnitsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCalendarCustomViewer = `-- name: InsertCalendarCustomViewer :exec
INSERT INTO calendar_custom_viewers (calendar_id, unit_id) VALUES ($1, $2)
`

type InsertCalendarCustomViewerParams struct {
	CalendarID int64
	UnitID     int64
}

func (q *Queries) InsertCalendarCustomViewer(ctx context.Context, arg InsertCalendarCustomViewerParams) error {
	_, err := q.db.Exec(ctx, insertCalendarCustomViewer, arg.CalendarID, arg.UnitID)
	return err
}

const listAllCalendars = `-- name: ListAllCalendars :many
SELECT id, slug, unit_id, name, creation_policy, visibility, participation, participant_visibility, color, sort_order, created_at, updated_at FROM calendars ORDER BY sort_order, name
`

func (q *Queries) ListAllCalendars(ctx context.Context) ([]Calendar, error) {
	rows, err := q.db.Query(ctx, listAllCalendars)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Calendar
	for rows.Next() {
		var i Calendar
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.UnitID,
			&i.Name,
			&i.CreationPolicy,
			&i.Visibility,
			&i.Participation,
			&i.ParticipantVisibility,
			&i.Color,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCalendarsByUnit = `-- name: ListCalendarsByUnit :many
SELECT id, slug, unit_id, name, creation_policy, visibility, participation, participant_visibility, color, sort_order, created_at, updated_at FROM calendars WHERE unit_id = $1 ORDER BY sort_order, name
`

func (q *Queries) ListCalendarsByUnit(ctx context.Context, unitID int64) ([]Calendar, error) {
	rows, err := q.db.Query(ctx, listCalendarsByUnit, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Calendar
	for rows.Next() {
		var i Calendar
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.UnitID,
			&i.Name,
			&i.CreationPolicy,
			&i.Visibility,
			&i.Participation,
			&i.ParticipantVisibility,
			&i.Color,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleCalendarsForUser = `-- name: ListVisibleCalendarsForUser :many
SELECT DISTINCT c.id, c.slug, c.unit_id, c.name, c.creation_policy, c.visibility,
    c.participation, c.participant_visibility, c.color, c.sort_order, c.created_at, c.updated_at
FROM calendars c
WHERE c.visibility = 'association'
   OR (c.visibility = 'unit' AND EXISTS(
       SELECT 1 FROM unit_group_bindings ugb
       JOIN user_idp_groups uig ON ugb.group_name = uig.group_name
       WHERE ugb.unit_id = c.unit_id AND uig.user_id = $1
   ))
   OR (c.visibility = 'custom' AND EXISTS(
       SELECT 1 FROM calendar_custom_viewers ccv
       JOIN unit_group_bindings ugb ON ccv.unit_id = ugb.unit_id
       JOIN user_idp_groups uig ON ugb.group_name = uig.group_name
       WHERE ccv.calendar_id = c.id AND uig.user_id = $1
   ))
ORDER BY c.sort_order, c.name
`

func (q *Queries) ListVisibleCalendarsForUser(ctx context.Context, userID int64) ([]Calendar, error) {
	rows, err := q.db.Query(ctx, listVisibleCalendarsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Calendar
	for rows.Next() {
		var i Calendar
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.UnitID,
			&i.Name,
			&i.CreationPolicy,
			&i.Visibility,
			&i.Participation,
			&i.ParticipantVisibility,
			&i.Color,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCalendar = `-- name: UpdateCalendar :one
UPDATE calendars SET
    name = $2,
    creation_policy = $3,
    visibility = $4,
    participation = $5,
    participant_visibility = $6,
    color = $7,
    sort_order = $8,
    updated_at = now()
WHERE id = $1
RETURNING id, slug, unit_id, name, creation_policy, visibility, participation, participant_visibility, color, sort_order, created_at, updated_at
`

type UpdateCalendarParams struct {
	ID                    int64
	Name                  string
	CreationPolicy        string
	Visibility            string
	Participation         string
	ParticipantVisibility string
	Color                 pgtype.Text
	SortOrder             int32
}

func (q *Queries) UpdateCalendar(ctx context.Context, arg UpdateCalendarParams) (Calendar, error) {
	row := q.db.QueryRow(ctx, updateCalendar,
		arg.ID,
		arg.Name,
		arg.CreationPolicy,
		arg.Visibility,
		arg.Participation,
		arg.ParticipantVisibility,
		arg.Color,
		arg.SortOrder,
	)
	var i Calendar
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.UnitID,
		&i.Name,
		&i.CreationPolicy,
		&i.Visibility,
		&i.Participation,
		&i.ParticipantVisibility,
		&i.Color,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
