// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (slug, calendar_id, name, type, starts_at, ends_at, location, description, response_deadline, recurrence_rule_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, slug, calendar_id, name, type, starts_at, ends_at, location, description, response_deadline, recurrence_rule_id, created_at, updated_at
`

type CreateEntryParams struct {
	Slug             string
	CalendarID       int64
	Name             string
	Type             string
	StartsAt         pgtype.Timestamptz
	EndsAt           pgtype.Timestamptz
	Location         pgtype.Text
	Description      pgtype.Text
	ResponseDeadline pgtype.Timestamptz
	RecurrenceRuleID pgtype.Int8
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, createEntry,
		arg.Slug,
		arg.CalendarID,
		arg.Name,
		arg.Type,
		arg.StartsAt,
		arg.EndsAt,
		arg.Location,
		arg.Description,
		arg.ResponseDeadline,
		arg.RecurrenceRuleID,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.CalendarID,
		&i.Name,
		&i.Type,
		&i.StartsAt,
		&i.EndsAt,
		&i.Location,
		&i.Description,
		&i.ResponseDeadline,
		&i.RecurrenceRuleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEntryAnnotation = `-- name: CreateEntryAnnotation :one
INSERT INTO entry_annotations (entry_id, kind, message)
VALUES ($1, $2, $3)
RETURNING id, entry_id, kind, message
`

type CreateEntryAnnotationParams struct {
	EntryID int64
	Kind    string
	Message string
}

func (q *Queries) CreateEntryAnnotation(ctx context.Context, arg CreateEntryAnnotationParams) (EntryAnnotation, error) {
	row := q.db.QueryRow(ctx, createEntryAnnotation, arg.EntryID, arg.Kind, arg.Message)
	var i EntryAnnotation
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.Kind,
		&i.Message,
	)
	return i, err
}

const deleteEntry = `-- name: DeleteEntry :exec
DELETE FROM entries WHERE id = $1
`

func (q *Queries) DeleteEntry(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteEntry, id)
	return err
}

const deleteMeetingAudienceUnits = `-- name: DeleteMeetingAudienceUnits :exec
DELETE FROM meeting_audience_units WHERE entry_id = $1
`

func (q *Queries) DeleteMeetingAudienceUnits(ctx context.Context, entryID int64) error {
	_, err := q.db.Exec(ctx, deleteMeetingAudienceUnits, entryID)
	return err
}

const getEntryByID = `-- name: GetEntryByID :one
SELECT id, slug, calendar_id, name, type, starts_at, ends_at, location, description, response_deadline, recurrence_rule_id, created_at, updated_at FROM entries WHERE id = $1
`

func (q *Queries) GetEntryByID(ctx context.Context, id int64) (Entry, error) {
	row := q.db.QueryRow(ctx, getEntryByID, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.CalendarID,
		&i.Name,
		&i.Type,
		&i.StartsAt,
		&i.EndsAt,
		&i.Location,
		&i.Description,
		&i.ResponseDeadline,
		&i.RecurrenceRuleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEntryBySlug = `-- name: GetEntryBySlug :one
SELECT id, slug, calendar_id, name, type, starts_at, ends_at, location, description, response_deadline, recurrence_rule_id, created_at, updated_at FROM entries WHERE slug = $1
`

func (q *Queries) GetEntryBySlug(ctx context.Context, slug string) (Entry, error) {
	row := q.db.QueryRow(ctx, getEntryBySlug, slug)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.CalendarID,
		&i.Name,
		&i.Type,
		&i.StartsAt,
		&i.EndsAt,
		&i.Location,
		&i.Description,
		&i.ResponseDeadline,
		&i.RecurrenceRuleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEntryForUpdate = `-- name: GetEntryForUpdate :one
SELECT e.id, e.slug, e.calendar_id, e.name, e.type, e.starts_at, e.ends_at, e.location, e.description, e.response_deadline, e.recurrence_rule_id, e.created_at, e.updated_at,
       c.name AS calendar_name,
       c.slug AS calendar_slug,
       c.color AS calendar_color,
       c.unit_id AS unit_id
FROM entries e
JOIN calendars c ON e.calendar_id = c.id
WHERE e.id = $1
FOR UPDATE OF e
`

type GetEntryForUpdateRow struct {
	ID               int64
	Slug             string
	CalendarID       int64
	Name             string
	Type             string
	StartsAt         pgtype.Timestamptz
	EndsAt           pgtype.Timestamptz
	Location         pgtype.Text
	Description      pgtype.Text
	ResponseDeadline pgtype.Timestamptz
	RecurrenceRuleID pgtype.Int8
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	CalendarName     string
	CalendarSlug     string
	CalendarColor    pgtype.Text
	UnitID           int64
}

func (q *Queries) GetEntryForUpdate(ctx context.Context, id int64) (GetEntryForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getEntryForUpdate, id)
	var i GetEntryForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.CalendarID,
		&i.Name,
		&i.Type,
		&i.StartsAt,
		&i.EndsAt,
		&i.Location,
		&i.Description,
		&i.ResponseDeadline,
		&i.RecurrenceRuleID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CalendarName,
		&i.CalendarSlug,
		&i.CalendarColor,
		&i.UnitID,
	)
	return i, err
}

const getEntryShiftDetails = `-- name: GetEntryShiftDetails :one
SELECT entry_id, required_participants, max_participants FROM entry_shift_details WHERE entry_id = $1
`

func (q *Queries) GetEntryShiftDetails(ctx context.Context, entryID int64) (EntryShiftDetail, error) {
	row := q.db.QueryRow(ctx, getEntryShiftDetails, entryID)
	var i EntryShiftDetail
	err := row.Scan(&i.EntryID, &i.RequiredParticipants, &i.MaxParticipants)
	return i, err
}

const getEntryWithCalendar = `-- name: GetEntryWithCalendar :one
SELECT e.id, e.slug, e.calendar_id, e.name, e.type, e.starts_at, e.ends_at, e.location, e.description, e.response_deadline, e.recurrence_rule_id, e.created_at, e.updated_at,
       c.name AS calendar_name,
       c.slug AS calendar_slug,
       c.color AS calendar_color,
       c.unit_id AS unit_id
FROM entries e
JOIN calendars c ON e.calendar_id = c.id
WHERE e.id = $1
`

type GetEntryWithCalendarRow struct {
	ID               int64
	Slug             string
	CalendarID       int64
	Name             string
	Type             string
	StartsAt         pgtype.Timestamptz
	EndsAt           pgtype.Timestamptz
	Location         pgtype.Text
	Description      pgtype.Text
	ResponseDeadline pgtype.Timestamptz
	RecurrenceRuleID pgtype.Int8
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	CalendarName     string
	CalendarSlug     string
	CalendarColor    pgtype.Text
	UnitID           int64
}

func (q *Queries) GetEntryWithCalendar(ctx context.Context, id int64) (GetEntryWithCalendarRow, error) {
	row := q.db.QueryRow(ctx, getEntryWithCalendar, id)
	var i GetEntryWithCalendarRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.CalendarID,
		&i.Name,
		&i.Type,
		&i.StartsAt,
		&i.EndsAt,
		&i.Location,
		&i.Description,
		&i.ResponseDeadline,
		&i.RecurrenceRuleID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CalendarName,
		&i.CalendarSlug,
		&i.CalendarColor,
		&i.UnitID,
	)
	return i, err
}

const getEntryWithCalendarBySlug = `-- name: GetEntryWithCalendarBySlug :one
SELECT e.id, e.slug, e.calendar_id, e.name, e.type, e.starts_at, e.ends_at, e.location, e.description, e.response_deadline, e.recurrence_rule_id, e.created_at, e.updated_at,
       c.name AS calendar_name,
       c.slug AS calendar_slug,
       c.color AS calendar_color,
       c.unit_id AS unit_id
FROM entries e
JOIN calendars c ON e.calendar_id = c.id
WHERE e.slug = $1
`

type GetEntryWithCalendarBySlugRow struct {
	ID               int64
	Slug             string
	CalendarID       int64
	Name             string
	Type             string
	StartsAt         pgtype.Timestamptz
	EndsAt           pgtype.Timestamptz
	Location         pgtype.Text
	Description      pgtype.Text
	ResponseDeadline pgtype.Timestamptz
	RecurrenceRuleID pgtype.Int8
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	CalendarName     string
	CalendarSlug     string
	CalendarColor    pgtype.Text
	UnitID           int64
}

func (q *Queries) GetEntryWithCalendarBySlug(ctx context.Context, slug string) (GetEntryWithCalendarBySlugRow, error) {
	row := q.db.QueryRow(ctx, getEntryWithCalendarBySlug, slug)
	var i GetEntryWithCalendarBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.CalendarID,
		&i.Name,
		&i.Type,
		&i.StartsAt,
		&i.EndsAt,
		&i.Location,
		&i.Description,
		&i.ResponseDeadline,
		&i.RecurrenceRuleID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CalendarName,
		&i.CalendarSlug,
		&i.CalendarColor,
		&i.UnitID,
	)
	return i, err
}

const getMeetingAudienceUnits = `-- name: GetMeetingAudienceUnits :many
SELECT unit_id FROM meeting_audience_units WHERE entry_id = $1
`

func (q *Queries) GetMeetingAudienceUnits(ctx context.Context, entryID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getMeetingAudienceUnits, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var unit_id int64
		if err := rows.Scan(&unit_id); err != nil {
			return nil, err
		}
		items = append(items, unit_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMeetingAudienceUnit = `-- name: InsertMeetingAudienceUnit :exec
INSERT INTO meeting_audience_units (entry_id, unit_id) VALUES ($1, $2)
`

type InsertMeetingAudienceUnitParams struct {
	EntryID int64
	UnitID  int64
}

func (q *Queries) InsertMeetingAudienceUnit(ctx context.Context, arg InsertMeetingAudienceUnitParams) error {
	_, err := q.db.Exec(ctx, insertMeetingAudienceUnit, arg.EntryID, arg.UnitID)
	return err
}

const listEntriesByCalendarAndDateRange = `-- name: ListEntriesByCalendarAndDateRange :many
SELECT id, slug, calendar_id, name, type, starts_at, ends_at, location, description, response_deadline, recurrence_rule_id, created_at, updated_at FROM entries
WHERE calendar_id = $1
  AND starts_at >= $2
  AND starts_at < $3
ORDER BY starts_at
`

type ListEntriesByCalendarAndDateRangeParams struct {
	CalendarID int64
	StartsAt   pgtype.Timestamptz
	StartsAt_2 pgtype.Timestamptz
}

func (q *Queries) ListEntriesByCalendarAndDateRange(ctx context.Context, arg ListEntriesByCalendarAndDateRangeParams) ([]Entry, error) {
	rows, err := q.db.Query(ctx, listEntriesByCalendarAndDateRange, arg.CalendarID, arg.StartsAt, arg.StartsAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.CalendarID,
			&i.Name,
			&i.Type,
			&i.StartsAt,
			&i.EndsAt,
			&i.Location,
			&i.Description,
			&i.ResponseDeadline,
			&i.RecurrenceRuleID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByCalendarWithCalendar = `-- name: ListEntriesByCalendarWithCalendar :many
SELECT e.id, e.slug, e.calendar_id, e.name, e.type, e.starts_at, e.ends_at, e.location, e.description, e.response_deadline, e.recurrence_rule_id, e.created_at, e.updated_at,
       c.name AS calendar_name,
       c.slug AS calendar_slug,
       c.color AS calendar_color,
       c.unit_id AS unit_id
FROM entries e
JOIN calendars c ON e.calendar_id = c.id
WHERE e.calendar_id = $1
  AND e.starts_at >= $2
  AND e.starts_at < $3
ORDER BY e.starts_at
`

type ListEntriesByCalendarWithCalendarParams struct {
	CalendarID int64
	StartsAt   pgtype.Timestamptz
	StartsAt_2 pgtype.Timestamptz
}

type ListEntriesByCalendarWithCalendarRow struct {
	ID               int64
	Slug             string
	CalendarID       int64
	Name             string
	Type             string
	StartsAt         pgtype.Timestamptz
	EndsAt           pgtype.Timestamptz
	Location         pgtype.Text
	Description      pgtype.Text
	ResponseDeadline pgtype.Timestamptz
	RecurrenceRuleID pgtype.Int8
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	CalendarName     string
	CalendarSlug     string
	CalendarColor    pgtype.Text
	UnitID           int64
}

func (q *Queries) ListEntriesByCalendarWithCalendar(ctx context.Context, arg ListEntriesByCalendarWithCalendarParams) ([]ListEntriesByCalendarWithCalendarRow, error) {
	rows, err := q.db.Query(ctx, listEntriesByCalendarWithCalendar, arg.CalendarID, arg.StartsAt, arg.StartsAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesByCalendarWithCalendarRow
	for rows.Next() {
		var i ListEntriesByCalendarWithCalendarRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.CalendarID,
			&i.Name,
			&i.Type,
			&i.StartsAt,
			&i.EndsAt,
			&i.Location,
			&i.Description,
			&i.ResponseDeadline,
			&i.RecurrenceRuleID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CalendarName,
			&i.CalendarSlug,
			&i.CalendarColor,
			&i.UnitID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByDateRange = `-- name: ListEntriesByDateRange :many
SELECT id, slug, calendar_id, name, type, starts_at, ends_at, location, description, response_deadline, recurrence_rule_id, created_at, updated_at FROM entries
WHERE starts_at >= $1 AND starts_at < $2
ORDER BY starts_at
`

type ListEntriesByDateRangeParams struct {
	StartsAt   pgtype.Timestamptz
	StartsAt_2 pgtype.Timestamptz
}

func (q *Queries) ListEntriesByDateRange(ctx context.Context, arg ListEntriesByDateRangeParams) ([]Entry, error) {
	rows, err := q.db.Query(ctx, listEntriesByDateRange, arg.StartsAt, arg.StartsAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.CalendarID,
			&i.Name,
			&i.Type,
			&i.StartsAt,
			&i.EndsAt,
			&i.Location,
			&i.Description,
			&i.ResponseDeadline,
			&i.RecurrenceRuleID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByRecurrenceRule = `-- name: ListEntriesByRecurrenceRule :many
SELECT id, slug, calendar_id, name, type, starts_at, ends_at, location, description, response_deadline, recurrence_rule_id, created_at, updated_at FROM entries WHERE recurrence_rule_id = $1 ORDER BY starts_at
`

func (q *Queries) ListEntriesByRecurrenceRule(ctx context.Context, recurrenceRuleID pgtype.Int8) ([]Entry, error) {
	rows, err := q.db.Query(ctx, listEntriesByRecurrenceRule, recurrenceRuleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.CalendarID,
			&i.Name,
			&i.Type,
			&i.StartsAt,
			&i.EndsAt,
			&i.Location,
			&i.Description,
			&i.ResponseDeadline,
			&i.RecurrenceRuleID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByUnit = `-- name: ListEntriesByUnit :many
SELECT e.id, e.slug, e.calendar_id, e.name, e.type, e.starts_at, e.ends_at, e.location, e.description, e.response_deadline, e.recurrence_rule_id, e.created_at, e.updated_at,
       c.name AS calendar_name,
       c.slug AS calendar_slug,
       c.color AS calendar_color,
       c.unit_id AS unit_id
FROM entries e
JOIN calendars c ON e.calendar_id = c.id
WHERE c.unit_id = $1
  AND e.starts_at >= $2
  AND e.starts_at < $3
ORDER BY e.starts_at
`

type ListEntriesByUnitParams struct {
	UnitID     int64
	StartsAt   pgtype.Timestamptz
	StartsAt_2 pgtype.Timestamptz
}

type ListEntriesByUnitRow struct {
	ID               int64
	Slug             string
	CalendarID       int64
	Name             string
	Type             string
	StartsAt         pgtype.Timestamptz
	EndsAt           pgtype.Timestamptz
	Location         pgtype.Text
	Description      pgtype.Text
	ResponseDeadline pgtype.Timestamptz
	RecurrenceRuleID pgtype.Int8
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	CalendarName     string
	CalendarSlug     string
	CalendarColor    pgtype.Text
	UnitID           int64
}

func (q *Queries) ListEntriesByUnit(ctx context.Context, arg ListEntriesByUnitParams) ([]ListEntriesByUnitRow, error) {
	rows, err := q.db.Query(ctx, listEntriesByUnit, arg.UnitID, arg.StartsAt, arg.StartsAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesByUnitRow
	for rows.Next() {
		var i ListEntriesByUnitRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.CalendarID,
			&i.Name,
			&i.Type,
			&i.StartsAt,
			&i.EndsAt,
			&i.Location,
			&i.Description,
			&i.ResponseDeadline,
			&i.RecurrenceRuleID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CalendarName,
			&i.CalendarSlug,
			&i.CalendarColor,
			&i.UnitID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByUser = `-- name: ListEntriesByUser :many
SELECT e.id, e.slug, e.calendar_id, e.name, e.type, e.starts_at, e.ends_at, e.location, e.description, e.response_deadline, e.recurrence_rule_id, e.created_at, e.updated_at,
       c.name AS calendar_name,
       c.slug AS calendar_slug,
       c.color AS calendar_color,
       c.unit_id AS unit_id
FROM entries e
JOIN calendars c ON e.calendar_id = c.id
JOIN attendances a ON a.entry_id = e.id
WHERE a.user_id = $1
  AND a.status IN ('accepted', 'pending')
  AND e.starts_at >= $2
  AND e.starts_at < $3
ORDER BY e.starts_at
`

type ListEntriesByUserParams struct {
	UserID     int64
	StartsAt   pgtype.Timestamptz
	StartsAt_2 pgtype.Timestamptz
}

type ListEntriesByUserRow struct {
	ID               int64
	Slug             string
	CalendarID       int64
	Name             string
	Type             string
	StartsAt         pgtype.Timestamptz
	EndsAt           pgtype.Timestamptz
	Location         pgtype.Text
	Description      pgtype.Text
	ResponseDeadline pgtype.Timestamptz
	RecurrenceRuleID pgtype.Int8
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	CalendarName     string
	CalendarSlug     string
	CalendarColor    pgtype.Text
	UnitID           int64
}

func (q *Queries) ListEntriesByUser(ctx context.Context, arg ListEntriesByUserParams) ([]ListEntriesByUserRow, error) {
	rows, err := q.db.Query(ctx, listEntriesByUser, arg.UserID, arg.StartsAt, arg.StartsAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesByUserRow
	for rows.Next() {
		var i ListEntriesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.CalendarID,
			&i.Name,
			&i.Type,
			&i.StartsAt,
			&i.EndsAt,
			&i.Location,
			&i.Description,
			&i.ResponseDeadline,
			&i.RecurrenceRuleID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CalendarName,
			&i.CalendarSlug,
			&i.CalendarColor,
			&i.UnitID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntryAnnotations = `-- name: ListEntryAnnotations :many
SELECT id, entry_id, kind, message FROM entry_annotations WHERE entry_id = $1
`

func (q *Queries) ListEntryAnnotations(ctx context.Context, entryID int64) ([]EntryAnnotation, error) {
	rows, err := q.db.Query(ctx, listEntryAnnotations, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntryAnnotation
	for rows.Next() {
		var i EntryAnnotation
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.Kind,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntry = `-- name: UpdateEntry :one
UPDATE entries SET
    name = $2,
    starts_at = $3,
    ends_at = $4,
    location = $5,
    description = $6,
    response_deadline = $7,
    updated_at = now()
WHERE id = $1
RETURNING id, slug, calendar_id, name, type, starts_at, ends_at, location, description, response_deadline, recurrence_rule_id, created_at, updated_at
`

type UpdateEntryParams struct {
	ID               int64
	Name             string
	StartsAt         pgtype.Timestamptz
	EndsAt           pgtype.Timestamptz
	Location         pgtype.Text
	Description      pgtype.Text
	ResponseDeadline pgtype.Timestamptz
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, updateEntry,
		arg.ID,
		arg.Name,
		arg.StartsAt,
		arg.EndsAt,
		arg.Location,
		arg.Description,
		arg.ResponseDeadline,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.CalendarID,
		&i.Name,
		&i.Type,
		&i.StartsAt,
		&i.EndsAt,
		&i.Location,
		&i.Description,
		&i.ResponseDeadline,
		&i.RecurrenceRuleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertEntryShiftDetails = `-- name: UpsertEntryShiftDetails :one
INSERT INTO entry_shift_details (entry_id, required_participants, max_participants)
VALUES ($1, $2, $3)
ON CONFLICT (entry_id) DO UPDATE SET
    required_participants = EXCLUDED.required_participants,
    max_participants = EXCLUDED.max_participants
RETURNING entry_id, required_participants, max_participants
`

type UpsertEntryShiftDetailsParams struct {
	EntryID              int64
	RequiredParticipants int32
	MaxParticipants      int32
}

func (q *Queries) UpsertEntryShiftDetails(ctx context.Context, arg UpsertEntryShiftDetailsParams) (EntryShiftDetail, error) {
	row := q.db.QueryRow(ctx, upsertEntryShiftDetails, arg.EntryID, arg.RequiredParticipants, arg.MaxParticipants)
	var i EntryShiftDetail
	err := row.Scan(&i.EntryID, &i.RequiredParticipants, &i.MaxParticipants)
	return i, err
}
