// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCalendarToEvent = `-- name: AddCalendarToEvent :exec
INSERT INTO event_calendars (event_id, calendar_id, sort_order)
VALUES ($1, $2, $3)
ON CONFLICT (event_id, calendar_id) DO UPDATE SET sort_order = EXCLUDED.sort_order
`

type AddCalendarToEventParams struct {
	EventID    int64
	CalendarID int64
	SortOrder  int32
}

func (q *Queries) AddCalendarToEvent(ctx context.Context, arg AddCalendarToEventParams) error {
	_, err := q.db.Exec(ctx, addCalendarToEvent, arg.EventID, arg.CalendarID, arg.SortOrder)
	return err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (slug, unit_id, name, start_date, end_date, website, description)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, slug, unit_id, name, start_date, end_date, website, description, created_at, updated_at
`

type CreateEventParams struct {
	Slug        string
	UnitID      int64
	Name        string
	StartDate   pgtype.Date
	EndDate     pgtype.Date
	Website     pgtype.Text
	Description pgtype.Text
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Slug,
		arg.UnitID,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
		arg.Website,
		arg.Description,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.UnitID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Website,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, slug, unit_id, name, start_date, end_date, website, description, created_at, updated_at FROM events WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.UnitID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Website,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventBySlug = `-- name: GetEventBySlug :one
SELECT id, slug, unit_id, name, start_date, end_date, website, description, created_at, updated_at FROM events WHERE slug = $1
`

func (q *Queries) GetEventBySlug(ctx context.Context, slug string) (Event, error) {
	row := q.db.QueryRow(ctx, getEventBySlug, slug)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.UnitID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Website,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEventCalendars = `-- name: ListEventCalendars :many
SELECT c.id, c.slug, c.unit_id, c.name, c.creation_policy, c.visibility, c.participation, c.participant_visibility, c.color, c.sort_order, c.created_at, c.updated_at FROM calendars c
JOIN event_calendars ec ON c.id = ec.calendar_id
WHERE ec.event_id = $1
ORDER BY ec.sort_order, c.name
`

func (q *Queries) ListEventCalendars(ctx context.Context, eventID int64) ([]Calendar, error) {
	rows, err := q.db.Query(ctx, listEventCalendars, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Calendar
	for rows.Next() {
		var i Calendar
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.UnitID,
			&i.Name,
			&i.CreationPolicy,
			&i.Visibility,
			&i.Participation,
			&i.ParticipantVisibility,
			&i.Color,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByUnit = `-- name: ListEventsByUnit :many
SELECT id, slug, unit_id, name, start_date, end_date, website, description, created_at, updated_at FROM events WHERE unit_id = $1 ORDER BY start_date DESC
`

func (q *Queries) ListEventsByUnit(ctx context.Context, unitID int64) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByUnit, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.UnitID,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
			&i.Website,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCalendarFromEvent = `-- name: RemoveCalendarFromEvent :exec
DELETE FROM event_calendars WHERE event_id = $1 AND calendar_id = $2
`

type RemoveCalendarFromEventParams struct {
	EventID    int64
	CalendarID int64
}

func (q *Queries) RemoveCalendarFromEvent(ctx context.Context, arg RemoveCalendarFromEventParams) error {
	_, err := q.db.Exec(ctx, removeCalendarFromEvent, arg.EventID, arg.CalendarID)
	return err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events SET
    name = $2,
    start_date = $3,
    end_date = $4,
    website = $5,
    description = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, slug, unit_id, name, start_date, end_date, website, description, created_at, updated_at
`

type UpdateEventParams struct {
	ID          int64
	Name        string
	StartDate   pgtype.Date
	EndDate     pgtype.Date
	Website     pgtype.Text
	Description pgtype.Text
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
		arg.Website,
		arg.Description,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.UnitID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Website,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
