// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: external_sources.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExternalSource = `-- name: CreateExternalSource :one
INSERT INTO external_sources (name, feed_url, calendar_id, refresh_interval, enabled)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, feed_url, calendar_id, refresh_interval, enabled, last_fetched_at, last_error, created_at, updated_at
`

type CreateExternalSourceParams struct {
	Name            string
	FeedUrl         string
	CalendarID      int64
	RefreshInterval pgtype.Interval
	Enabled         bool
}

func (q *Queries) CreateExternalSource(ctx context.Context, arg CreateExternalSourceParams) (ExternalSource, error) {
	row := q.db.QueryRow(ctx, createExternalSource,
		arg.Name,
		arg.FeedUrl,
		arg.CalendarID,
		arg.RefreshInterval,
		arg.Enabled,
	)
	var i ExternalSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FeedUrl,
		&i.CalendarID,
		&i.RefreshInterval,
		&i.Enabled,
		&i.LastFetchedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExternalSourceByID = `-- name: GetExternalSourceByID :one
SELECT id, name, feed_url, calendar_id, refresh_interval, enabled, last_fetched_at, last_error, created_at, updated_at FROM external_sources WHERE id = $1
`

func (q *Queries) GetExternalSourceByID(ctx context.Context, id int64) (ExternalSource, error) {
	row := q.db.QueryRow(ctx, getExternalSourceByID, id)
	var i ExternalSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FeedUrl,
		&i.CalendarID,
		&i.RefreshInterval,
		&i.Enabled,
		&i.LastFetchedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledExternalSources = `-- name: ListEnabledExternalSources :many
SELECT id, name, feed_url, calendar_id, refresh_interval, enabled, last_fetched_at, last_error, created_at, updated_at FROM external_sources WHERE enabled = true
`

func (q *Queries) ListEnabledExternalSources(ctx context.Context) ([]ExternalSource, error) {
	rows, err := q.db.Query(ctx, listEnabledExternalSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExternalSource
	for rows.Next() {
		var i ExternalSource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FeedUrl,
			&i.CalendarID,
			&i.RefreshInterval,
			&i.Enabled,
			&i.LastFetchedAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExternalEntriesBySource = `-- name: ListExternalEntriesBySource :many
SELECT id, external_source_id, uid, summary, starts_at, ends_at, location, description, raw_ical, fetched_at FROM external_entries WHERE external_source_id = $1 ORDER BY starts_at
`

func (q *Queries) ListExternalEntriesBySource(ctx context.Context, externalSourceID int64) ([]ExternalEntry, error) {
	rows, err := q.db.Query(ctx, listExternalEntriesBySource, externalSourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExternalEntry
	for rows.Next() {
		var i ExternalEntry
		if err := rows.Scan(
			&i.ID,
			&i.ExternalSourceID,
			&i.Uid,
			&i.Summary,
			&i.StartsAt,
			&i.EndsAt,
			&i.Location,
			&i.Description,
			&i.RawIcal,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExternalSourcesByCalendar = `-- name: ListExternalSourcesByCalendar :many
SELECT id, name, feed_url, calendar_id, refresh_interval, enabled, last_fetched_at, last_error, created_at, updated_at FROM external_sources WHERE calendar_id = $1
`

func (q *Queries) ListExternalSourcesByCalendar(ctx context.Context, calendarID int64) ([]ExternalSource, error) {
	rows, err := q.db.Query(ctx, listExternalSourcesByCalendar, calendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExternalSource
	for rows.Next() {
		var i ExternalSource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FeedUrl,
			&i.CalendarID,
			&i.RefreshInterval,
			&i.Enabled,
			&i.LastFetchedAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExternalSource = `-- name: UpdateExternalSource :one
UPDATE external_sources SET
    name = $2,
    feed_url = $3,
    refresh_interval = $4,
    enabled = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, name, feed_url, calendar_id, refresh_interval, enabled, last_fetched_at, last_error, created_at, updated_at
`

type UpdateExternalSourceParams struct {
	ID              int64
	Name            string
	FeedUrl         string
	RefreshInterval pgtype.Interval
	Enabled         bool
}

func (q *Queries) UpdateExternalSource(ctx context.Context, arg UpdateExternalSourceParams) (ExternalSource, error) {
	row := q.db.QueryRow(ctx, updateExternalSource,
		arg.ID,
		arg.Name,
		arg.FeedUrl,
		arg.RefreshInterval,
		arg.Enabled,
	)
	var i ExternalSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FeedUrl,
		&i.CalendarID,
		&i.RefreshInterval,
		&i.Enabled,
		&i.LastFetchedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateExternalSourceFetchStatus = `-- name: UpdateExternalSourceFetchStatus :exec
UPDATE external_sources SET
    last_fetched_at = now(),
    last_error = $2,
    updated_at = now()
WHERE id = $1
`

type UpdateExternalSourceFetchStatusParams struct {
	ID        int64
	LastError pgtype.Text
}

func (q *Queries) UpdateExternalSourceFetchStatus(ctx context.Context, arg UpdateExternalSourceFetchStatusParams) error {
	_, err := q.db.Exec(ctx, updateExternalSourceFetchStatus, arg.ID, arg.LastError)
	return err
}

const upsertExternalEntry = `-- name: UpsertExternalEntry :one
INSERT INTO external_entries (external_source_id, uid, summary, starts_at, ends_at, location, description, raw_ical, fetched_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
ON CONFLICT (external_source_id, uid) DO UPDATE SET
    summary = EXCLUDED.summary,
    starts_at = EXCLUDED.starts_at,
    ends_at = EXCLUDED.ends_at,
    location = EXCLUDED.location,
    description = EXCLUDED.description,
    raw_ical = EXCLUDED.raw_ical,
    fetched_at = now()
RETURNING id, external_source_id, uid, summary, starts_at, ends_at, location, description, raw_ical, fetched_at
`

type UpsertExternalEntryParams struct {
	ExternalSourceID int64
	Uid              string
	Summary          pgtype.Text
	StartsAt         pgtype.Timestamptz
	EndsAt           pgtype.Timestamptz
	Location         pgtype.Text
	Description      pgtype.Text
	RawIcal          pgtype.Text
}

func (q *Queries) UpsertExternalEntry(ctx context.Context, arg UpsertExternalEntryParams) (ExternalEntry, error) {
	row := q.db.QueryRow(ctx, upsertExternalEntry,
		arg.ExternalSourceID,
		arg.Uid,
		arg.Summary,
		arg.StartsAt,
		arg.EndsAt,
		arg.Location,
		arg.Description,
		arg.RawIcal,
	)
	var i ExternalEntry
	err := row.Scan(
		&i.ID,
		&i.ExternalSourceID,
		&i.Uid,
		&i.Summary,
		&i.StartsAt,
		&i.EndsAt,
		&i.Location,
		&i.Description,
		&i.RawIcal,
		&i.FetchedAt,
	)
	return i, err
}
