// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feed_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFeedToken = `-- name: CreateFeedToken :one
INSERT INTO feed_tokens (user_id, scope, scope_id, token)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, scope, scope_id, token, created_at, revoked_at
`

type CreateFeedTokenParams struct {
	UserID  int64
	Scope   string
	ScopeID pgtype.Int8
	Token   string
}

func (q *Queries) CreateFeedToken(ctx context.Context, arg CreateFeedTokenParams) (FeedToken, error) {
	row := q.db.QueryRow(ctx, createFeedToken,
		arg.UserID,
		arg.Scope,
		arg.ScopeID,
		arg.Token,
	)
	var i FeedToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Scope,
		&i.ScopeID,
		&i.Token,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getFeedTokenByToken = `-- name: GetFeedTokenByToken :one
SELECT id, user_id, scope, scope_id, token, created_at, revoked_at FROM feed_tokens WHERE token = $1 AND revoked_at IS NULL
`

func (q *Queries) GetFeedTokenByToken(ctx context.Context, token string) (FeedToken, error) {
	row := q.db.QueryRow(ctx, getFeedTokenByToken, token)
	var i FeedToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Scope,
		&i.ScopeID,
		&i.Token,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listFeedTokensByUser = `-- name: ListFeedTokensByUser :many
SELECT id, user_id, scope, scope_id, token, created_at, revoked_at FROM feed_tokens WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListFeedTokensByUser(ctx context.Context, userID int64) ([]FeedToken, error) {
	rows, err := q.db.Query(ctx, listFeedTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedToken
	for rows.Next() {
		var i FeedToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Scope,
			&i.ScopeID,
			&i.Token,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeFeedToken = `-- name: RevokeFeedToken :exec
UPDATE feed_tokens SET revoked_at = now() WHERE id = $1
`

func (q *Queries) RevokeFeedToken(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, revokeFeedToken, id)
	return err
}
