// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Attendance struct {
	ID          int64
	EntryID     int64
	UserID      int64
	Status      string
	Confirmed   bool
	Note        pgtype.Text
	RespondedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Calendar struct {
	ID                    int64
	Slug                  string
	UnitID                int64
	Name                  string
	CreationPolicy        string
	Visibility            string
	Participation         string
	ParticipantVisibility string
	Color                 pgtype.Text
	SortOrder             int32
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type CalendarCustomViewer struct {
	CalendarID int64
	UnitID     int64
}

type Entry struct {
	ID               int64
	Slug             string
	CalendarID       int64
	Name             string
	Type             string
	StartsAt         pgtype.Timestamptz
	EndsAt           pgtype.Timestamptz
	Location         pgtype.Text
	Description      pgtype.Text
	ResponseDeadline pgtype.Timestamptz
	RecurrenceRuleID pgtype.Int8
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type EntryAnnotation struct {
	ID      int64
	EntryID int64
	Kind    string
	Message string
}

type EntryShiftDetail struct {
	EntryID              int64
	RequiredParticipants int32
	MaxParticipants      int32
}

type Event struct {
	ID          int64
	Slug        string
	UnitID      int64
	Name        string
	StartDate   pgtype.Date
	EndDate     pgtype.Date
	Website     pgtype.Text
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type EventCalendar struct {
	EventID    int64
	CalendarID int64
	SortOrder  int32
}

type ExternalEntry struct {
	ID               int64
	ExternalSourceID int64
	Uid              string
	Summary          pgtype.Text
	StartsAt         pgtype.Timestamptz
	EndsAt           pgtype.Timestamptz
	Location         pgtype.Text
	Description      pgtype.Text
	RawIcal          pgtype.Text
	FetchedAt        pgtype.Timestamptz
}

type ExternalSource struct {
	ID              int64
	Name            string
	FeedUrl         string
	CalendarID      int64
	RefreshInterval pgtype.Interval
	Enabled         bool
	LastFetchedAt   pgtype.Timestamptz
	LastError       pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type FeedToken struct {
	ID        int64
	UserID    int64
	Scope     string
	ScopeID   pgtype.Int8
	Token     string
	CreatedAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

type MeetingAudienceUnit struct {
	EntryID int64
	UnitID  int64
}

type Notification struct {
	ID         int64
	UserID     int64
	EntryID    pgtype.Int8
	EventType  string
	Channel    string
	Status     string
	Payload    []byte
	Error      pgtype.Text
	RetryCount int32
	SentAt     pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type NotificationConfig struct {
	ID         int64
	CalendarID int64
	EventType  string
	Enabled    bool
	LeadTime   pgtype.Interval
}

type RecurrenceRule struct {
	ID                 int64
	TemplateGroupID    int64
	PatternType        string
	PatternParams      []byte
	FirstOccurrence    pgtype.Date
	AutoCreateHorizon  int32
	Enabled            bool
	WeekendAction      string
	WeekendWarningText pgtype.Text
	HolidayAction      string
	HolidayWarningText pgtype.Text
	LastEvaluatedAt    pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type SubstitutionRequest struct {
	ID              int64
	AttendanceID    int64
	ClaimedByUserID pgtype.Int8
	ClaimedAt       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

type Template struct {
	ID                     int64
	TemplateGroupID        int64
	Name                   string
	Type                   string
	StartOffset            pgtype.Interval
	Duration               pgtype.Interval
	RequiredParticipants   pgtype.Int4
	MaxParticipants        pgtype.Int4
	Description            pgtype.Text
	ResponseDeadlineOffset pgtype.Interval
	SortOrder              int32
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type TemplateGroup struct {
	ID            int64
	UnitID        int64
	CalendarID    int64
	Name          string
	BaseStartTime pgtype.Time
	Location      pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Unit struct {
	ID           int64
	Name         string
	Slug         string
	Description  pgtype.Text
	LogoPath     pgtype.Text
	ContactEmail pgtype.Text
	AdminGroup   pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type UnitGroupBinding struct {
	UnitID    int64
	GroupName string
}

type User struct {
	ID           int64
	IdpSubject   string
	Username     string
	DisplayName  string
	Email        string
	Timezone     pgtype.Text
	Locale       pgtype.Text
	IsAssocAdmin bool
	LastLoginAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type UserIdpGroup struct {
	UserID    int64
	GroupName string
}

type UserNotificationPreference struct {
	ID        int64
	UserID    int64
	EventType string
	Channel   string
	Enabled   bool
}

type Webhook struct {
	ID        int64
	UnitID    pgtype.Int8
	Name      string
	Url       string
	Secret    pgtype.Text
	Enabled   bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
