// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, entry_id, event_type, channel, payload)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, entry_id, event_type, channel, status, payload, error, retry_count, sent_at, created_at
`

type CreateNotificationParams struct {
	UserID    int64
	EntryID   pgtype.Int8
	EventType string
	Channel   string
	Payload   []byte
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.EntryID,
		arg.EventType,
		arg.Channel,
		arg.Payload,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EntryID,
		&i.EventType,
		&i.Channel,
		&i.Status,
		&i.Payload,
		&i.Error,
		&i.RetryCount,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const getNotificationConfigsByCalendar = `-- name: GetNotificationConfigsByCalendar :many
SELECT id, calendar_id, event_type, enabled, lead_time FROM notification_configs WHERE calendar_id = $1
`

func (q *Queries) GetNotificationConfigsByCalendar(ctx context.Context, calendarID int64) ([]NotificationConfig, error) {
	rows, err := q.db.Query(ctx, getNotificationConfigsByCalendar, calendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationConfig
	for rows.Next() {
		var i NotificationConfig
		if err := rows.Scan(
			&i.ID,
			&i.CalendarID,
			&i.EventType,
			&i.Enabled,
			&i.LeadTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserNotificationPreferences = `-- name: GetUserNotificationPreferences :many
SELECT id, user_id, event_type, channel, enabled FROM user_notification_preferences WHERE user_id = $1
`

func (q *Queries) GetUserNotificationPreferences(ctx context.Context, userID int64) ([]UserNotificationPreference, error) {
	rows, err := q.db.Query(ctx, getUserNotificationPreferences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserNotificationPreference
	for rows.Next() {
		var i UserNotificationPreference
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventType,
			&i.Channel,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingNotifications = `-- name: ListPendingNotifications :many
SELECT id, user_id, entry_id, event_type, channel, status, payload, error, retry_count, sent_at, created_at FROM notifications
WHERE status IN ('pending', 'retrying')
ORDER BY created_at
LIMIT $1
`

func (q *Queries) ListPendingNotifications(ctx context.Context, limit int32) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listPendingNotifications, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EntryID,
			&i.EventType,
			&i.Channel,
			&i.Status,
			&i.Payload,
			&i.Error,
			&i.RetryCount,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationStatus = `-- name: UpdateNotificationStatus :exec
UPDATE notifications SET
    status = $2,
    error = $3,
    retry_count = CASE WHEN $2 = 'retrying' THEN retry_count + 1 ELSE retry_count END,
    sent_at = CASE WHEN $2 = 'sent' THEN now() ELSE sent_at END
WHERE id = $1
`

type UpdateNotificationStatusParams struct {
	ID     int64
	Status string
	Error  pgtype.Text
}

func (q *Queries) UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) error {
	_, err := q.db.Exec(ctx, updateNotificationStatus, arg.ID, arg.Status, arg.Error)
	return err
}

const upsertNotificationConfig = `-- name: UpsertNotificationConfig :one
INSERT INTO notification_configs (calendar_id, event_type, enabled, lead_time)
VALUES ($1, $2, $3, $4)
ON CONFLICT (calendar_id, event_type) DO UPDATE SET
    enabled = EXCLUDED.enabled,
    lead_time = EXCLUDED.lead_time
RETURNING id, calendar_id, event_type, enabled, lead_time
`

type UpsertNotificationConfigParams struct {
	CalendarID int64
	EventType  string
	Enabled    bool
	LeadTime   pgtype.Interval
}

func (q *Queries) UpsertNotificationConfig(ctx context.Context, arg UpsertNotificationConfigParams) (NotificationConfig, error) {
	row := q.db.QueryRow(ctx, upsertNotificationConfig,
		arg.CalendarID,
		arg.EventType,
		arg.Enabled,
		arg.LeadTime,
	)
	var i NotificationConfig
	err := row.Scan(
		&i.ID,
		&i.CalendarID,
		&i.EventType,
		&i.Enabled,
		&i.LeadTime,
	)
	return i, err
}

const upsertUserNotificationPreference = `-- name: UpsertUserNotificationPreference :one
INSERT INTO user_notification_preferences (user_id, event_type, channel, enabled)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, event_type, channel) DO UPDATE SET enabled = EXCLUDED.enabled
RETURNING id, user_id, event_type, channel, enabled
`

type UpsertUserNotificationPreferenceParams struct {
	UserID    int64
	EventType string
	Channel   string
	Enabled   bool
}

func (q *Queries) UpsertUserNotificationPreference(ctx context.Context, arg UpsertUserNotificationPreferenceParams) (UserNotificationPreference, error) {
	row := q.db.QueryRow(ctx, upsertUserNotificationPreference,
		arg.UserID,
		arg.EventType,
		arg.Channel,
		arg.Enabled,
	)
	var i UserNotificationPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventType,
		&i.Channel,
		&i.Enabled,
	)
	return i, err
}
