// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRecurrenceRule = `-- name: CreateRecurrenceRule :one
INSERT INTO recurrence_rules (template_group_id, pattern_type, pattern_params, first_occurrence, auto_create_horizon, enabled, weekend_action, weekend_warning_text, holiday_action, holiday_warning_text)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, template_group_id, pattern_type, pattern_params, first_occurrence, auto_create_horizon, enabled, weekend_action, weekend_warning_text, holiday_action, holiday_warning_text, last_evaluated_at, created_at, updated_at
`

type CreateRecurrenceRuleParams struct {
	TemplateGroupID    int64
	PatternType        string
	PatternParams      []byte
	FirstOccurrence    pgtype.Date
	AutoCreateHorizon  int32
	Enabled            bool
	WeekendAction      string
	WeekendWarningText pgtype.Text
	HolidayAction      string
	HolidayWarningText pgtype.Text
}

func (q *Queries) CreateRecurrenceRule(ctx context.Context, arg CreateRecurrenceRuleParams) (RecurrenceRule, error) {
	row := q.db.QueryRow(ctx, createRecurrenceRule,
		arg.TemplateGroupID,
		arg.PatternType,
		arg.PatternParams,
		arg.FirstOccurrence,
		arg.AutoCreateHorizon,
		arg.Enabled,
		arg.WeekendAction,
		arg.WeekendWarningText,
		arg.HolidayAction,
		arg.HolidayWarningText,
	)
	var i RecurrenceRule
	err := row.Scan(
		&i.ID,
		&i.TemplateGroupID,
		&i.PatternType,
		&i.PatternParams,
		&i.FirstOccurrence,
		&i.AutoCreateHorizon,
		&i.Enabled,
		&i.WeekendAction,
		&i.WeekendWarningText,
		&i.HolidayAction,
		&i.HolidayWarningText,
		&i.LastEvaluatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (template_group_id, name, type, start_offset, duration, required_participants, max_participants, description, response_deadline_offset, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, template_group_id, name, type, start_offset, duration, required_participants, max_participants, description, response_deadline_offset, sort_order, created_at, updated_at
`

type CreateTemplateParams struct {
	TemplateGroupID        int64
	Name                   string
	Type                   string
	StartOffset            pgtype.Interval
	Duration               pgtype.Interval
	RequiredParticipants   pgtype.Int4
	MaxParticipants        pgtype.Int4
	Description            pgtype.Text
	ResponseDeadlineOffset pgtype.Interval
	SortOrder              int32
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.TemplateGroupID,
		arg.Name,
		arg.Type,
		arg.StartOffset,
		arg.Duration,
		arg.RequiredParticipants,
		arg.MaxParticipants,
		arg.Description,
		arg.ResponseDeadlineOffset,
		arg.SortOrder,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.TemplateGroupID,
		&i.Name,
		&i.Type,
		&i.StartOffset,
		&i.Duration,
		&i.RequiredParticipants,
		&i.MaxParticipants,
		&i.Description,
		&i.ResponseDeadlineOffset,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTemplateGroup = `-- name: CreateTemplateGroup :one
INSERT INTO template_groups (unit_id, calendar_id, name, base_start_time, location)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, unit_id, calendar_id, name, base_start_time, location, created_at, updated_at
`

type CreateTemplateGroupParams struct {
	UnitID        int64
	CalendarID    int64
	Name          string
	BaseStartTime pgtype.Time
	Location      pgtype.Text
}

func (q *Queries) CreateTemplateGroup(ctx context.Context, arg CreateTemplateGroupParams) (TemplateGroup, error) {
	row := q.db.QueryRow(ctx, createTemplateGroup,
		arg.UnitID,
		arg.CalendarID,
		arg.Name,
		arg.BaseStartTime,
		arg.Location,
	)
	var i TemplateGroup
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.CalendarID,
		&i.Name,
		&i.BaseStartTime,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM templates WHERE id = $1
`

func (q *Queries) DeleteTemplate(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTemplate, id)
	return err
}

const deleteTemplateGroup = `-- name: DeleteTemplateGroup :exec
DELETE FROM template_groups WHERE id = $1
`

func (q *Queries) DeleteTemplateGroup(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTemplateGroup, id)
	return err
}

const getRecurrenceRuleByID = `-- name: GetRecurrenceRuleByID :one
SELECT id, template_group_id, pattern_type, pattern_params, first_occurrence, auto_create_horizon, enabled, weekend_action, weekend_warning_text, holiday_action, holiday_warning_text, last_evaluated_at, created_at, updated_at FROM recurrence_rules WHERE id = $1
`

func (q *Queries) GetRecurrenceRuleByID(ctx context.Context, id int64) (RecurrenceRule, error) {
	row := q.db.QueryRow(ctx, getRecurrenceRuleByID, id)
	var i RecurrenceRule
	err := row.Scan(
		&i.ID,
		&i.TemplateGroupID,
		&i.PatternType,
		&i.PatternParams,
		&i.FirstOccurrence,
		&i.AutoCreateHorizon,
		&i.Enabled,
		&i.WeekendAction,
		&i.WeekendWarningText,
		&i.HolidayAction,
		&i.HolidayWarningText,
		&i.LastEvaluatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateGroupByID = `-- name: GetTemplateGroupByID :one
SELECT id, unit_id, calendar_id, name, base_start_time, location, created_at, updated_at FROM template_groups WHERE id = $1
`

func (q *Queries) GetTemplateGroupByID(ctx context.Context, id int64) (TemplateGroup, error) {
	row := q.db.QueryRow(ctx, getTemplateGroupByID, id)
	var i TemplateGroup
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.CalendarID,
		&i.Name,
		&i.BaseStartTime,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledRecurrenceRules = `-- name: ListEnabledRecurrenceRules :many
SELECT id, template_group_id, pattern_type, pattern_params, first_occurrence, auto_create_horizon, enabled, weekend_action, weekend_warning_text, holiday_action, holiday_warning_text, last_evaluated_at, created_at, updated_at FROM recurrence_rules WHERE enabled = true
`

func (q *Queries) ListEnabledRecurrenceRules(ctx context.Context) ([]RecurrenceRule, error) {
	rows, err := q.db.Query(ctx, listEnabledRecurrenceRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecurrenceRule
	for rows.Next() {
		var i RecurrenceRule
		if err := rows.Scan(
			&i.ID,
			&i.TemplateGroupID,
			&i.PatternType,
			&i.PatternParams,
			&i.FirstOccurrence,
			&i.AutoCreateHorizon,
			&i.Enabled,
			&i.WeekendAction,
			&i.WeekendWarningText,
			&i.HolidayAction,
			&i.HolidayWarningText,
			&i.LastEvaluatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurrenceRulesByTemplateGroup = `-- name: ListRecurrenceRulesByTemplateGroup :many
SELECT id, template_group_id, pattern_type, pattern_params, first_occurrence, auto_create_horizon, enabled, weekend_action, weekend_warning_text, holiday_action, holiday_warning_text, last_evaluated_at, created_at, updated_at FROM recurrence_rules WHERE template_group_id = $1
`

func (q *Queries) ListRecurrenceRulesByTemplateGroup(ctx context.Context, templateGroupID int64) ([]RecurrenceRule, error) {
	rows, err := q.db.Query(ctx, listRecurrenceRulesByTemplateGroup, templateGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecurrenceRule
	for rows.Next() {
		var i RecurrenceRule
		if err := rows.Scan(
			&i.ID,
			&i.TemplateGroupID,
			&i.PatternType,
			&i.PatternParams,
			&i.FirstOccurrence,
			&i.AutoCreateHorizon,
			&i.Enabled,
			&i.WeekendAction,
			&i.WeekendWarningText,
			&i.HolidayAction,
			&i.HolidayWarningText,
			&i.LastEvaluatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateGroupsByCalendar = `-- name: ListTemplateGroupsByCalendar :many
SELECT id, unit_id, calendar_id, name, base_start_time, location, created_at, updated_at FROM template_groups WHERE calendar_id = $1 ORDER BY name
`

func (q *Queries) ListTemplateGroupsByCalendar(ctx context.Context, calendarID int64) ([]TemplateGroup, error) {
	rows, err := q.db.Query(ctx, listTemplateGroupsByCalendar, calendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TemplateGroup
	for rows.Next() {
		var i TemplateGroup
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.CalendarID,
			&i.Name,
			&i.BaseStartTime,
			&i.Location,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplatesByGroup = `-- name: ListTemplatesByGroup :many
SELECT id, template_group_id, name, type, start_offset, duration, required_participants, max_participants, description, response_deadline_offset, sort_order, created_at, updated_at FROM templates WHERE template_group_id = $1 ORDER BY sort_order, name
`

func (q *Queries) ListTemplatesByGroup(ctx context.Context, templateGroupID int64) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplatesByGroup, templateGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.TemplateGroupID,
			&i.Name,
			&i.Type,
			&i.StartOffset,
			&i.Duration,
			&i.RequiredParticipants,
			&i.MaxParticipants,
			&i.Description,
			&i.ResponseDeadlineOffset,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecurrenceRule = `-- name: UpdateRecurrenceRule :one
UPDATE recurrence_rules SET
    pattern_type = $2,
    pattern_params = $3,
    first_occurrence = $4,
    auto_create_horizon = $5,
    enabled = $6,
    weekend_action = $7,
    weekend_warning_text = $8,
    holiday_action = $9,
    holiday_warning_text = $10,
    updated_at = now()
WHERE id = $1
RETURNING id, template_group_id, pattern_type, pattern_params, first_occurrence, auto_create_horizon, enabled, weekend_action, weekend_warning_text, holiday_action, holiday_warning_text, last_evaluated_at, created_at, updated_at
`

type UpdateRecurrenceRuleParams struct {
	ID                 int64
	PatternType        string
	PatternParams      []byte
	FirstOccurrence    pgtype.Date
	AutoCreateHorizon  int32
	Enabled            bool
	WeekendAction      string
	WeekendWarningText pgtype.Text
	HolidayAction      string
	HolidayWarningText pgtype.Text
}

func (q *Queries) UpdateRecurrenceRule(ctx context.Context, arg UpdateRecurrenceRuleParams) (RecurrenceRule, error) {
	row := q.db.QueryRow(ctx, updateRecurrenceRule,
		arg.ID,
		arg.PatternType,
		arg.PatternParams,
		arg.FirstOccurrence,
		arg.AutoCreateHorizon,
		arg.Enabled,
		arg.WeekendAction,
		arg.WeekendWarningText,
		arg.HolidayAction,
		arg.HolidayWarningText,
	)
	var i RecurrenceRule
	err := row.Scan(
		&i.ID,
		&i.TemplateGroupID,
		&i.PatternType,
		&i.PatternParams,
		&i.FirstOccurrence,
		&i.AutoCreateHorizon,
		&i.Enabled,
		&i.WeekendAction,
		&i.WeekendWarningText,
		&i.HolidayAction,
		&i.HolidayWarningText,
		&i.LastEvaluatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRecurrenceRuleLastEvaluated = `-- name: UpdateRecurrenceRuleLastEvaluated :exec
UPDATE recurrence_rules SET last_evaluated_at = now() WHERE id = $1
`

func (q *Queries) UpdateRecurrenceRuleLastEvaluated(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateRecurrenceRuleLastEvaluated, id)
	return err
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE templates SET
    name = $2,
    type = $3,
    start_offset = $4,
    duration = $5,
    required_participants = $6,
    max_participants = $7,
    description = $8,
    response_deadline_offset = $9,
    sort_order = $10,
    updated_at = now()
WHERE id = $1
RETURNING id, template_group_id, name, type, start_offset, duration, required_participants, max_participants, description, response_deadline_offset, sort_order, created_at, updated_at
`

type UpdateTemplateParams struct {
	ID                     int64
	Name                   string
	Type                   string
	StartOffset            pgtype.Interval
	Duration               pgtype.Interval
	RequiredParticipants   pgtype.Int4
	MaxParticipants        pgtype.Int4
	Description            pgtype.Text
	ResponseDeadlineOffset pgtype.Interval
	SortOrder              int32
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, updateTemplate,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.StartOffset,
		arg.Duration,
		arg.RequiredParticipants,
		arg.MaxParticipants,
		arg.Description,
		arg.ResponseDeadlineOffset,
		arg.SortOrder,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.TemplateGroupID,
		&i.Name,
		&i.Type,
		&i.StartOffset,
		&i.Duration,
		&i.RequiredParticipants,
		&i.MaxParticipants,
		&i.Description,
		&i.ResponseDeadlineOffset,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTemplateGroup = `-- name: UpdateTemplateGroup :one
UPDATE template_groups SET
    name = $2,
    base_start_time = $3,
    location = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, unit_id, calendar_id, name, base_start_time, location, created_at, updated_at
`

type UpdateTemplateGroupParams struct {
	ID            int64
	Name          string
	BaseStartTime pgtype.Time
	Location      pgtype.Text
}

func (q *Queries) UpdateTemplateGroup(ctx context.Context, arg UpdateTemplateGroupParams) (TemplateGroup, error) {
	row := q.db.QueryRow(ctx, updateTemplateGroup,
		arg.ID,
		arg.Name,
		arg.BaseStartTime,
		arg.Location,
	)
	var i TemplateGroup
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.CalendarID,
		&i.Name,
		&i.BaseStartTime,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
