// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: unit_group_bindings.sql

package db

import (
	"context"
)

const deleteUnitGroupBindings = `-- name: DeleteUnitGroupBindings :exec
DELETE FROM unit_group_bindings WHERE unit_id = $1
`

func (q *Queries) DeleteUnitGroupBindings(ctx context.Context, unitID int64) error {
	_, err := q.db.Exec(ctx, deleteUnitGroupBindings, unitID)
	return err
}

const getUnitGroupBindings = `-- name: GetUnitGroupBindings :many
SELECT group_name FROM unit_group_bindings WHERE unit_id = $1
`

func (q *Queries) GetUnitGroupBindings(ctx context.Context, unitID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, getUnitGroupBindings, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var group_name string
		if err := rows.Scan(&group_name); err != nil {
			return nil, err
		}
		items = append(items, group_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUnitGroupBinding = `-- name: InsertUnitGroupBinding :exec
INSERT INTO unit_group_bindings (unit_id, group_name) VALUES ($1, $2)
`

type InsertUnitGroupBindingParams struct {
	UnitID    int64
	GroupName string
}

func (q *Queries) InsertUnitGroupBinding(ctx context.Context, arg InsertUnitGroupBindingParams) error {
	_, err := q.db.Exec(ctx, insertUnitGroupBinding, arg.UnitID, arg.GroupName)
	return err
}

const isUserAdminOfUnit = `-- name: IsUserAdminOfUnit :one
SELECT EXISTS(
    SELECT 1 FROM user_idp_groups uig
    JOIN units u ON uig.group_name = u.admin_group
    WHERE uig.user_id = $1 AND u.id = $2
) AS is_admin
`

type IsUserAdminOfUnitParams struct {
	UserID int64
	ID     int64
}

func (q *Queries) IsUserAdminOfUnit(ctx context.Context, arg IsUserAdminOfUnitParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserAdminOfUnit, arg.UserID, arg.ID)
	var is_admin bool
	err := row.Scan(&is_admin)
	return is_admin, err
}

const isUserMemberOfUnit = `-- name: IsUserMemberOfUnit :one
SELECT EXISTS(
    SELECT 1 FROM user_idp_groups uig
    JOIN unit_group_bindings ugb ON uig.group_name = ugb.group_name
    WHERE uig.user_id = $1 AND ugb.unit_id = $2
) AS is_member
`

type IsUserMemberOfUnitParams struct {
	UserID int64
	UnitID int64
}

func (q *Queries) IsUserMemberOfUnit(ctx context.Context, arg IsUserMemberOfUnitParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserMemberOfUnit, arg.UserID, arg.UnitID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const listUnitsForUser = `-- name: ListUnitsForUser :many
SELECT DISTINCT u.id, u.name, u.slug, u.description, u.logo_path, u.contact_email, u.admin_group, u.created_at, u.updated_at FROM units u
JOIN unit_group_bindings ugb ON u.id = ugb.unit_id
JOIN user_idp_groups uig ON ugb.group_name = uig.group_name
WHERE uig.user_id = $1
ORDER BY u.name
`

func (q *Queries) ListUnitsForUser(ctx context.Context, userID int64) ([]Unit, error) {
	rows, err := q.db.Query(ctx, listUnitsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Unit
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.LogoPath,
			&i.ContactEmail,
			&i.AdminGroup,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
