// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: units.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUnit = `-- name: CreateUnit :one
INSERT INTO units (name, slug, description, logo_path, contact_email, admin_group)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, slug, description, logo_path, contact_email, admin_group, created_at, updated_at
`

type CreateUnitParams struct {
	Name         string
	Slug         string
	Description  pgtype.Text
	LogoPath     pgtype.Text
	ContactEmail pgtype.Text
	AdminGroup   pgtype.Text
}

func (q *Queries) CreateUnit(ctx context.Context, arg CreateUnitParams) (Unit, error) {
	row := q.db.QueryRow(ctx, createUnit,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.LogoPath,
		arg.ContactEmail,
		arg.AdminGroup,
	)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LogoPath,
		&i.ContactEmail,
		&i.AdminGroup,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUnit = `-- name: DeleteUnit :exec
DELETE FROM units WHERE id = $1
`

func (q *Queries) DeleteUnit(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUnit, id)
	return err
}

const getUnitByID = `-- name: GetUnitByID :one
SELECT id, name, slug, description, logo_path, contact_email, admin_group, created_at, updated_at FROM units WHERE id = $1
`

func (q *Queries) GetUnitByID(ctx context.Context, id int64) (Unit, error) {
	row := q.db.QueryRow(ctx, getUnitByID, id)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LogoPath,
		&i.ContactEmail,
		&i.AdminGroup,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUnitBySlug = `-- name: GetUnitBySlug :one
SELECT id, name, slug, description, logo_path, contact_email, admin_group, created_at, updated_at FROM units WHERE slug = $1
`

func (q *Queries) GetUnitBySlug(ctx context.Context, slug string) (Unit, error) {
	row := q.db.QueryRow(ctx, getUnitBySlug, slug)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LogoPath,
		&i.ContactEmail,
		&i.AdminGroup,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUnits = `-- name: ListUnits :many
SELECT id, name, slug, description, logo_path, contact_email, admin_group, created_at, updated_at FROM units ORDER BY name
`

func (q *Queries) ListUnits(ctx context.Context) ([]Unit, error) {
	rows, err := q.db.Query(ctx, listUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Unit
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.LogoPath,
			&i.ContactEmail,
			&i.AdminGroup,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUnit = `-- name: UpdateUnit :one
UPDATE units SET
    name = $2,
    description = $3,
    logo_path = $4,
    contact_email = $5,
    admin_group = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, name, slug, description, logo_path, contact_email, admin_group, created_at, updated_at
`

type UpdateUnitParams struct {
	ID           int64
	Name         string
	Description  pgtype.Text
	LogoPath     pgtype.Text
	ContactEmail pgtype.Text
	AdminGroup   pgtype.Text
}

func (q *Queries) UpdateUnit(ctx context.Context, arg UpdateUnitParams) (Unit, error) {
	row := q.db.QueryRow(ctx, updateUnit,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.LogoPath,
		arg.ContactEmail,
		arg.AdminGroup,
	)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LogoPath,
		&i.ContactEmail,
		&i.AdminGroup,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
