// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, idp_subject, username, display_name, email, timezone, locale, is_assoc_admin, last_login_at, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.IdpSubject,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Timezone,
		&i.Locale,
		&i.IsAssocAdmin,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, idp_subject, username, display_name, email, timezone, locale, is_assoc_admin, last_login_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.IdpSubject,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Timezone,
		&i.Locale,
		&i.IsAssocAdmin,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByIDPSubject = `-- name: GetUserByIDPSubject :one
SELECT id, idp_subject, username, display_name, email, timezone, locale, is_assoc_admin, last_login_at, created_at, updated_at FROM users WHERE idp_subject = $1
`

func (q *Queries) GetUserByIDPSubject(ctx context.Context, idpSubject string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIDPSubject, idpSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.IdpSubject,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Timezone,
		&i.Locale,
		&i.IsAssocAdmin,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPreferences = `-- name: UpdateUserPreferences :one
UPDATE users SET
    timezone = $2,
    locale = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, idp_subject, username, display_name, email, timezone, locale, is_assoc_admin, last_login_at, created_at, updated_at
`

type UpdateUserPreferencesParams struct {
	ID       int64
	Timezone pgtype.Text
	Locale   pgtype.Text
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPreferences, arg.ID, arg.Timezone, arg.Locale)
	var i User
	err := row.Scan(
		&i.ID,
		&i.IdpSubject,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Timezone,
		&i.Locale,
		&i.IsAssocAdmin,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (idp_subject, username, display_name, email, is_assoc_admin, last_login_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (idp_subject) DO UPDATE SET
    username = EXCLUDED.username,
    display_name = EXCLUDED.display_name,
    email = EXCLUDED.email,
    is_assoc_admin = EXCLUDED.is_assoc_admin,
    last_login_at = now(),
    updated_at = now()
RETURNING id, idp_subject, username, display_name, email, timezone, locale, is_assoc_admin, last_login_at, created_at, updated_at
`

type UpsertUserParams struct {
	IdpSubject   string
	Username     string
	DisplayName  string
	Email        string
	IsAssocAdmin bool
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.IdpSubject,
		arg.Username,
		arg.DisplayName,
		arg.Email,
		arg.IsAssocAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.IdpSubject,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Timezone,
		&i.Locale,
		&i.IsAssocAdmin,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
