// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_idp_groups.sql

package db

import (
	"context"
)

const deleteUserIDPGroups = `-- name: DeleteUserIDPGroups :exec
DELETE FROM user_idp_groups WHERE user_id = $1
`

func (q *Queries) DeleteUserIDPGroups(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserIDPGroups, userID)
	return err
}

const getUserIDPGroups = `-- name: GetUserIDPGroups :many
SELECT group_name FROM user_idp_groups WHERE user_id = $1
`

func (q *Queries) GetUserIDPGroups(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserIDPGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var group_name string
		if err := rows.Scan(&group_name); err != nil {
			return nil, err
		}
		items = append(items, group_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUserIDPGroup = `-- name: InsertUserIDPGroup :exec
INSERT INTO user_idp_groups (user_id, group_name) VALUES ($1, $2)
`

type InsertUserIDPGroupParams struct {
	UserID    int64
	GroupName string
}

func (q *Queries) InsertUserIDPGroup(ctx context.Context, arg InsertUserIDPGroupParams) error {
	_, err := q.db.Exec(ctx, insertUserIDPGroup, arg.UserID, arg.GroupName)
	return err
}

const isUserInGroup = `-- name: IsUserInGroup :one
SELECT EXISTS(
    SELECT 1 FROM user_idp_groups
    WHERE user_id = $1 AND group_name = $2
) AS is_member
`

type IsUserInGroupParams struct {
	UserID    int64
	GroupName string
}

func (q *Queries) IsUserInGroup(ctx context.Context, arg IsUserInGroupParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserInGroup, arg.UserID, arg.GroupName)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}
