// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (unit_id, name, url, secret, enabled)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, unit_id, name, url, secret, enabled, created_at, updated_at
`

type CreateWebhookParams struct {
	UnitID  pgtype.Int8
	Name    string
	Url     string
	Secret  pgtype.Text
	Enabled bool
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, createWebhook,
		arg.UnitID,
		arg.Name,
		arg.Url,
		arg.Secret,
		arg.Enabled,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.Name,
		&i.Url,
		&i.Secret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :exec
DELETE FROM webhooks WHERE id = $1
`

func (q *Queries) DeleteWebhook(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteWebhook, id)
	return err
}

const listAssociationWebhooks = `-- name: ListAssociationWebhooks :many
SELECT id, unit_id, name, url, secret, enabled, created_at, updated_at FROM webhooks WHERE unit_id IS NULL AND enabled = true
`

func (q *Queries) ListAssociationWebhooks(ctx context.Context) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listAssociationWebhooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Webhook
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.Name,
			&i.Url,
			&i.Secret,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooksByUnit = `-- name: ListWebhooksByUnit :many
SELECT id, unit_id, name, url, secret, enabled, created_at, updated_at FROM webhooks WHERE unit_id = $1 AND enabled = true
`

func (q *Queries) ListWebhooksByUnit(ctx context.Context, unitID pgtype.Int8) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listWebhooksByUnit, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Webhook
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.Name,
			&i.Url,
			&i.Secret,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhook = `-- name: UpdateWebhook :one
UPDATE webhooks SET
    name = $2,
    url = $3,
    secret = $4,
    enabled = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, unit_id, name, url, secret, enabled, created_at, updated_at
`

type UpdateWebhookParams struct {
	ID      int64
	Name    string
	Url     string
	Secret  pgtype.Text
	Enabled bool
}

func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, updateWebhook,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.Secret,
		arg.Enabled,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.Name,
		&i.Url,
		&i.Secret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
